// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/metrics.proto

/*
Package metrics is a generated protocol buffer package.

It is generated from these files:
	protobuf/metrics.proto

It has these top-level messages:
	Empty
	Device
	FeedItem
*/
package metrics

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Device struct {
	Id        int32       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Latitude  float64     `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64     `protobuf:"fixed64,4,opt,name=longitude" json:"longitude,omitempty"`
	TempF     int32       `protobuf:"varint,5,opt,name=temp_f,json=tempF" json:"temp_f,omitempty"`
	Feed      []*FeedItem `protobuf:"bytes,6,rep,name=feed" json:"feed,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Device) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Device) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Device) GetTempF() int32 {
	if m != nil {
		return m.TempF
	}
	return 0
}

func (m *Device) GetFeed() []*FeedItem {
	if m != nil {
		return m.Feed
	}
	return nil
}

type FeedItem struct {
	Ts    int64   `protobuf:"varint,1,opt,name=ts" json:"ts,omitempty"`
	Pm_25 float64 `protobuf:"fixed64,2,opt,name=pm_25,json=pm25" json:"pm_25,omitempty"`
}

func (m *FeedItem) Reset()                    { *m = FeedItem{} }
func (m *FeedItem) String() string            { return proto.CompactTextString(m) }
func (*FeedItem) ProtoMessage()               {}
func (*FeedItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FeedItem) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *FeedItem) GetPm_25() float64 {
	if m != nil {
		return m.Pm_25
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*Device)(nil), "Device")
	proto.RegisterType((*FeedItem)(nil), "FeedItem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DeviceMetrics service

type DeviceMetricsClient interface {
	AddDeviceMetrics(ctx context.Context, in *Device, opts ...grpc.CallOption) (*Empty, error)
}

type deviceMetricsClient struct {
	cc *grpc.ClientConn
}

func NewDeviceMetricsClient(cc *grpc.ClientConn) DeviceMetricsClient {
	return &deviceMetricsClient{cc}
}

func (c *deviceMetricsClient) AddDeviceMetrics(ctx context.Context, in *Device, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/DeviceMetrics/AddDeviceMetrics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DeviceMetrics service

type DeviceMetricsServer interface {
	AddDeviceMetrics(context.Context, *Device) (*Empty, error)
}

func RegisterDeviceMetricsServer(s *grpc.Server, srv DeviceMetricsServer) {
	s.RegisterService(&_DeviceMetrics_serviceDesc, srv)
}

func _DeviceMetrics_AddDeviceMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceMetricsServer).AddDeviceMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DeviceMetrics/AddDeviceMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceMetricsServer).AddDeviceMetrics(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceMetrics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DeviceMetrics",
	HandlerType: (*DeviceMetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDeviceMetrics",
			Handler:    _DeviceMetrics_AddDeviceMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/metrics.proto",
}

func init() { proto.RegisterFile("protobuf/metrics.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xd9, 0xfc, 0xd9, 0x36, 0x23, 0x8a, 0x8c, 0x28, 0x4b, 0x51, 0x08, 0xf1, 0x92, 0x53,
	0x0a, 0xd1, 0x7e, 0x00, 0x41, 0x0b, 0x1e, 0xbc, 0xec, 0x17, 0x28, 0x6d, 0x77, 0x22, 0x0b, 0xdd,
	0x66, 0x69, 0xa6, 0x82, 0xdf, 0xc5, 0x0f, 0x2b, 0x9d, 0xa0, 0xe2, 0x6d, 0xde, 0xef, 0x1d, 0xe6,
	0xbd, 0x07, 0x37, 0xf1, 0xd0, 0x73, 0xbf, 0x39, 0x76, 0xf3, 0x40, 0x7c, 0xf0, 0xdb, 0xa1, 0x11,
	0x50, 0x4d, 0x20, 0x7f, 0x09, 0x91, 0x3f, 0xab, 0x2f, 0x05, 0xfa, 0x99, 0x3e, 0xfc, 0x96, 0xf0,
	0x02, 0x12, 0xef, 0x8c, 0x2a, 0x55, 0x9d, 0xdb, 0xc4, 0x3b, 0x44, 0xc8, 0xf6, 0xeb, 0x40, 0x26,
	0x29, 0x55, 0x5d, 0x58, 0xb9, 0x71, 0x06, 0xd3, 0xdd, 0x9a, 0x3d, 0x1f, 0x1d, 0x99, 0xb4, 0x54,
	0xb5, 0xb2, 0xbf, 0x1a, 0x6f, 0xa1, 0xd8, 0xf5, 0xfb, 0xf7, 0xd1, 0xcc, 0xc4, 0xfc, 0x03, 0x78,
	0x0d, 0x9a, 0x29, 0xc4, 0x55, 0x67, 0x72, 0xf9, 0x90, 0x9f, 0xd4, 0x12, 0xef, 0x20, 0xeb, 0x88,
	0x9c, 0xd1, 0x65, 0x5a, 0x9f, 0xb5, 0x45, 0xb3, 0x24, 0x72, 0xaf, 0x4c, 0xc1, 0x0a, 0xae, 0xe6,
	0x30, 0xfd, 0x21, 0xa7, 0x7c, 0x3c, 0x48, 0xbe, 0xd4, 0x26, 0x3c, 0xe0, 0x15, 0xe4, 0x31, 0xac,
	0xda, 0x85, 0x04, 0x54, 0x36, 0x8b, 0xa1, 0x5d, 0xb4, 0x8f, 0x70, 0x3e, 0xd6, 0x79, 0x1b, 0xfb,
	0xe2, 0x3d, 0x5c, 0x3e, 0x39, 0xf7, 0x9f, 0x4d, 0x9a, 0x51, 0xcf, 0x74, 0x23, 0x2b, 0x6c, 0xb4,
	0xac, 0xf2, 0xf0, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x81, 0x13, 0xfc, 0x2f, 0x01, 0x00, 0x00,
}
